# Generated by Django 5.0.4 on 2024-09-16 08:38

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(default='0000000000', max_length=13, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=50)),
                ('author', models.JSONField(default='', max_length=50)),
                ('publisher', models.CharField(default='', max_length=50)),
                ('pubdate', models.CharField(max_length=10)),
                ('cover', models.CharField(default='', max_length=100)),
                ('douban_url', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_major', models.CharField(default='', max_length=50)),
                ('user_department', models.CharField(default='', max_length=50)),
                ('user_credit', models.IntegerField(default=100)),
                ('user_indate', models.CharField(default='', max_length=4)),
                ('user_avatar', models.ImageField(blank=True, default='Avatar/DefaultAvatar.png', upload_to='Avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(db_index=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationCode',
            fields=[
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_index=True, default='', max_length=50)),
                ('department', models.CharField(default='', max_length=50)),
            ],
            options={
                'unique_together': {('course_name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Usebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(default='', max_length=10)),
                ('semester', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'unique_together': {('course', 'teacher', 'course', 'school_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200)),
                ('com_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usebook')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookisbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'unique_together': {('userid', 'bookisbn')},
            },
        ),
        migrations.CreateModel(
            name='UpScoreUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('useBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usebook')),
            ],
            options={
                'unique_together': {('user', 'useBook')},
            },
        ),
        migrations.CreateModel(
            name='DownScoreUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('useBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usebook')),
            ],
            options={
                'unique_together': {('user', 'useBook')},
            },
        ),
    ]
