# Generated by Django 5.0.4 on 2024-07-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='info',
            field=models.CharField(max_length=200),
        ),
    ]
