# Generated by Django 5.0.4 on 2024-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.JSONField(default='', max_length=50),
        ),
    ]
