# Generated by Django 5.0.4 on 2024-07-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usebook_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'department')},
        ),
    ]
