# Generated by Django 5.0.4 on 2024-07-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_course_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_it', models.IntegerField(default=0)),
                ('dont_get_it', models.IntegerField(default=0)),
                ('useBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
