# Generated by Django 5.0.4 on 2024-07-07 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreUserRelation',
            fields=[
                ('useBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
