# Generated by Django 5.0.4 on 2024-07-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_comment_com_date_alter_user_user_indate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_indate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
