# Generated by Django 5.0.4 on 2024-07-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_comment_com_date_alter_user_user_indate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
