# Generated by Django 5.0.4 on 2024-07-07 14:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=api.models.generate_unique_code, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
