# Generated by Django 5.0.4 on 2024-07-08 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_downscoreuserrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='downscoreuserrelation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upscoreuserrelation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downscoreuserrelation',
            name='useBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usebook'),
        ),
        migrations.AlterField(
            model_name='upscoreuserrelation',
            name='useBook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usebook'),
        ),
    ]
