# Generated by Django 5.0.4 on 2024-07-08 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_downscoreuserrelation_id_upscoreuserrelation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downscoreuserrelation',
            unique_together={('user', 'useBook')},
        ),
        migrations.AlterUniqueTogether(
            name='upscoreuserrelation',
            unique_together={('user', 'useBook')},
        ),
    ]
