# Generated by Django 5.0.4 on 2024-07-09 08:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_downscoreuserrelation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationCode',
            fields=[
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
