# Generated by Django 5.0.4 on 2024-07-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_profile_user_avatar_profile_user_indate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.AddField(
            model_name='comment',
            name='usebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usebook'),
            preserve_default=False,
        ),
    ]
